config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'devise/custom_registrations' }

  get '/admin', to: redirect('/admin/questions')
  namespace :admin do
    match 'questions/import', to: 'questions#import', via: [:get, :post]
    resources :questions
    get '/applicants' => 'applicants#index'
    resources :applicants
  end

  get '/dashboard', to: redirect('/')
  namespace :dashboard do
    resources :dashboard
    get '/quiz' => 'quiz#take'
    post '/quiz' => 'quiz#respond'
  end

  root 'dashboard/dashboard#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_and_belongs_to_many :answers

  accepts_nested_attributes_for :answers, allow_destroy: true

  validates :answers, minimum_collection_size: {size: 2}

  def self.import_from_json(json)
    json.each do |question_text, answer_image_urls|
      q = Question.new(text: question_text)
      answer_image_urls.each do |image_url|
        q.answers.build(image_url: image_url)
      end
      q.save
      q.correct_answer_id = q.answers.first.id
      q.save
    end

  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::AdminController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order('created_at DESC')
  end

  def import
      if request.post?
        json = JSON.parse(params[:json])
        Question.import_from_json(json)
        redirect_to admin_questions_path
      end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    4.times {
      @question.answers.build
    }
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        @question.correct_answer_id = @question.answers.first.id
        @question.save
        format.html { redirect_to admin_question_path(@question), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: admin_question_path(@question) }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to admin_question_path(@question), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_question_path(@question) }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to admin_questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:id, :text, answers_attributes: [:id, :image_url, :_destroy])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    #4.times { @question.answers.build }
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:id, :text, answers_attributes: [:id, :image_url, :_destroy])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/questions/_form.html.erb
<%= form_for([:admin, @question]) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

        <ul>
            <% @question.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>

  <%= f.text_field :text, autofocus: true, placeholder: 'Enter question here' %>

  <h2>Answers (Image URLs)</h2>

  <%= f.fields_for :answers do |answer| %>
    <%= answer.text_field :image_url, placeholder: "image url" %>
  <% end %>

  <%= f.submit 'Save Question', class: 'btn' %>

<% end %>

app/views/admin/questions/edit.html.erb
<h2>Edit Question</h2>
<%= render 'form' %>

app/views/admin/questions/import.html.erb
<h3>Import Questions</h3>

<%= form_tag 'import', :id => 'import-questions' do %>
  <p>At least one question, at least two answers each, and the first answer the correct one.</p>

  <%= text_area_tag 'json', '
    {
      "Cutest Kitten": [
      "http://placekitten.com/g/200/300",
      "http://lorempixel.com/300/200/sports/5/",
      "http://lorempixel.com/300/200/sports/7/",
      "http://lorempixel.com/300/200/sports/9/"
      ]
    }
    ', rows: 10
  %>
  <%= submit_tag 'Import from JSON', class: 'btn stretch-on-phones' %>
<% end %>

app/views/admin/questions/index.html.erb
<div class="top-buttons">
  <%= link_to 'New Question', new_admin_question_path, class: 'btn simple stretch-50-on-phones' %>
  <%= link_to 'Import Questions', admin_questions_import_path, class: 'btn simple stretch-50-on-phones' %>
</div>

<ul class="choices">
    <% @questions.each do |question| %>
      <li>
        <a href='<%= admin_question_path(question) %>'>
            <div class="text">
                <%= question.text %>
            </div>
            <div class="img-box">
                <img src='<%= question.answers.find(question.correct_answer_id).image_url %>'>
            </div>
        </a>
      </li>
    <% end %>
</ul>



<br>

app/views/admin/questions/new.html.erb
<%= link_to '< Back to All Questions', admin_questions_path, class: 'btn simple stretch-on-phones' %>

<h2>New Question</h2>

<%= render 'form' %>

app/views/admin/questions/show.html.erb
<div class="top-buttons">
  <%= link_to '< Back to All', admin_questions_path, class: 'btn simple stretch-33-on-phones' %>
  <%= link_to 'Modify', edit_admin_question_path(@question), class: 'btn simple stretch-33-on-phones' %>
  <%= link_to 'Delete', admin_question_path(@question), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn simple stretch-33-on-phones' %>
</div>

<h2><%= @question.text %>?</h2>

<ul class="choices">
    <% @question.answers.each do |answer| %>
      <li>
          <a>
              <% if answer.id == @question.correct_answer_id %>
                <div class="short text">
                    Correct Answer
                </div>
              <% end %>
              <div class="img-box">
                  <img src='<%= answer.image_url %>'>
              </div>
          </a>
      </li>
    <% end %>
</ul>