config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'devise/custom_registrations' }

  get '/admin', to: redirect('/admin/questions')
  namespace :admin do
    match 'questions/import', to: 'questions#import', via: [:get, :post]
    resources :questions
    get '/applicants' => 'applicants#index'
    resources :applicants
  end

  get '/dashboard', to: redirect('/')
  namespace :dashboard do
    resources :dashboard
    get '/quiz' => 'quiz#take'
    post '/quiz' => 'quiz#respond'
  end

  root 'dashboard/dashboard#index'

end

app/views/layouts/_dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>JobQuiz Dashboard</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<%= render 'dashboard/nav', locals: {title: ''} %>

<div class="container">
    <%= render 'dashboard/stage_partials/stage_progress_bar' %>

    <%= render 'dashboard/stage_partials/current_stage_instructions' %>

    <%= yield %>
</div>


</body>
</html>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>JobQuiz Admin</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<%= render 'dashboard/nav', locals: {title: 'Admin'} %>

<div class="admin container">

  <ul class="tabs">
    <li class="stretch-50-on-phones<%=' selected' if controller.controller_name == 'questions' %>">
        <a href="<%= admin_questions_path %>">Questions</a>
    </li>
    <li class="stretch-50-on-phones<%=' selected' if controller.controller_name == 'applicants' %>">
        <a href="<%= admin_applicants_path %>">Applicants</a>
    </li>
  </ul>

  <%= yield %>

</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobQuiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>JobQuiz Dashboard</title>
    <%= stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="hi"></div>

<div class="header">
    <%= render 'dashboard/session_links' %>
</div>

<%= render 'dashboard/stage_partials/stage_progress_bar' %>

<%= render 'dashboard/stage_partials/current_stage_instructions' %>

<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<%= render 'layouts/dashboard' %>

app/views/layouts/quiz.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>JobQuiz Quiz</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.3/moment.js"></script>
    <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<div class="container">
    <%= yield %>
</div>


</body>
</html>